version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data-dev:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecretPassword
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "9000:80"
    links:
      - postgres